name: Documentation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Generate Documentation
        uses: SwiftDocOrg/swift-doc@master
        with:
          base-url: /monki-map-model/
          format: html
          inputs: Sources/MonkiMapModel
          module-name: MonkiMapModel
          output: Documentation
      - name: Update Permissions
        run: 'sudo chown --recursive $USER Documentation'
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.SWIFT_DOC_ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: Documentation
